version: '3.5'

services:
  mysql:
    image: mysql:8.0.19
    volumes:
      - ./cache/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ROOT}
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
volumes:
  mysql:
  phpmyadmin:
